### ISSUE TITLE
directory list empty

### ISSUE THREAD

**Issue by Tecko71** [glk1001/glk1001.github.io#4]
I use kodi nexus on android. There I installed spotify but the list stays empty. No directory yo albums or artists. I filled in the credentials but it does not work.

023-08-11 23:26:03.134 T:5466     info <general>: plugin.audio.spotify:utils:get_token --> b"Couldn't request authentication token. Username/password error? If you're using a facebook account with Spotify, make sure to generate a device account/password in the Spotify accountdetails."

**Comment by glk1001** [comment]
Yes, sorry for the bad news but the spotty binary is not built for Android. Maybe one day, but at the moment I have no idea how to make this work on Android.
