### ISSUE TITLE
Wrong binary name for arm-hf

### ISSUE THREAD

**Issue by KickerTom** [glk1001/glk1001.github.io#5]
Thanks for working on this plugin, much appreciated.
Tried this plugin on OSMC-Vero4k, which is arm32 platform. After installing, the log shows an error opening the spotty library, looking for spotty-hf. However the binary in the archive is called now spotty-muslhf.
After updating the binary name in the utils.py file, function get_spotty_binary, the plugin seems to work well (authentication passes, can search for tracks, can play tracks).

**Comment by glk1001** [comment]
Just added version 1.3.5 with a fix like you did. Beware though, lots of cleaning and refactoring but I've tested on Windows and Linux x86 and it's OK. Can you give it a try?

**Comment by KickerTom** [comment]
Sorry for the delay, holidays interfering :-). Just verified 1.3.5, works like a charm, thanks a lot.
