### ISSUE TITLE
Volume is too low

### ISSUE THREAD

**Issue by cooleyd17** [glk1001/glk1001.github.io#6]
Volume is lower than other streaming add-ons. Is there an option to disable volume leveling or increase the volume?

**Comment by glk1001** [comment]
There isn't a direct option to do this but can you try this for me:

In the python file ".kodi/addons/plugin.audio.spotify/resources/lib/spotty_audio_streamer.py' comment the code like this:

`SPOTTY_STREAMING_DEFAULT_ARGS = [`
`    "--bitrate",`
`    SPOTIFY_BITRATE,`
`#    "--enable-volume-normalisation",`
`#    "--normalisation-gain-type",`
`#    SPOTTY_GAIN_TYPE,`
`    "--initial-volume",`
`    SPOTTY_INITIAL_VOLUME,`
`]`

The comments disable Spotify audio normalization. Restart Kodi and see if that makes a difference. (You can also try playing with "SPOTTY_INITIAL_VOLUME" but I had no luck.)

If this works I could add a plugin setting.

**Comment by cooleyd17** [comment]
I think disabling the audio normalization made a big difference! It is now much louder with this code. After that I also set initial volume to 100 instead of 50 but it was hard to tell if it made any difference. I think a plugin setting for audio normalization would be great. Thank you very much.

**Comment by cooleyd17** [comment]
My issue is resolved

**Comment by glk1001** [comment]
Added setting to turn off Spotify normalization.
